CREATE TABLE `user` (
	`USERID` VARCHAR(20) NULL DEFAULT NULL,
	`USERPASSWORD` VARCHAR(20) NULL DEFAULT NULL,
	`USERNAME` VARCHAR(20) NULL DEFAULT NULL,
	`USERAGE` INT(20) NULL DEFAULT NULL,
	`USERGENDER` VARCHAR(20) NULL DEFAULT NULL,
	`USEREMAIL` VARCHAR(50) NULL DEFAULT NULL,
	`USERPROFILE` VARCHAR(50) NULL DEFAULT NULL
);